// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package oe.mid.soa.bean;

public final class BeanServiceImpl_Stub
    extends java.rmi.server.RemoteStub
    implements oe.mid.soa.bean.client.BeanService, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_ivBean_0;
    
    static {
	try {
	    $method_ivBean_0 = oe.mid.soa.bean.client.BeanService.class.getMethod("ivBean", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public BeanServiceImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of ivBean(String)
    public oe.mid.soa.bean.OecBean ivBean(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_ivBean_0, new java.lang.Object[] {$param_String_1}, -2441154157863217461L);
	    return ((oe.mid.soa.bean.OecBean) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
