DROP TABLE IF EXISTS iss.producttotal;
DROP TABLE IF EXISTS iss.producttotal2;
ALTER TABLE `iss`.`t_productcategories` DROP INDEX `FK_t_productcategories_categoriesId`,
 DROP FOREIGN KEY `FK_t_productcategories_categoriesId`;
ALTER TABLE `iss`.`t_product` DROP INDEX `FK_t_product_categoriesId`
, DROP INDEX `IDX_productCode`,
 DROP FOREIGN KEY `FK_t_product_categoriesId`; 
DROP TABLE IF EXISTS iss.t_adjustmentdetailfrom;
DROP TABLE IF EXISTS iss.t_adjustmentfrom;
DROP TABLE IF EXISTS iss.t_allocatecargodetail;
DROP TABLE IF EXISTS iss.t_allocatecargo;
DROP TABLE IF EXISTS iss.t_areadepartment;
DROP TABLE IF EXISTS iss.t_area;
DROP TABLE IF EXISTS iss.t_clientpricelevel;
DROP TABLE IF EXISTS iss.t_collectionpayment;
DROP TABLE IF EXISTS iss.t_groupcategories;
DROP TABLE IF EXISTS iss.t_group;
DROP TABLE IF EXISTS iss.t_groupterminaldetail;
DROP TABLE IF EXISTS iss.t_groupterminal;
DROP TABLE IF EXISTS iss.t_incentivepaymentcash;
DROP TABLE IF EXISTS iss.t_indentoperate;
DROP TABLE IF EXISTS iss.t_indentpayment;
DROP TABLE IF EXISTS iss.t_indentdetail;
DROP TABLE IF EXISTS iss.t_indent;
DROP TABLE IF EXISTS iss.t_instoragedetail;
DROP TABLE IF EXISTS iss.t_instorage;
DROP TABLE IF EXISTS iss.t_managepayment;
DROP TABLE IF EXISTS iss.t_otherpayment;
DROP TABLE IF EXISTS iss.t_outstoragedetail;
DROP TABLE IF EXISTS iss.t_outstorage;
DROP TABLE IF EXISTS iss.t_payment;
DROP TABLE IF EXISTS iss.t_planoperate;
DROP TABLE IF EXISTS iss.t_plandetail;
DROP TABLE IF EXISTS iss.t_plan;
DROP TABLE IF EXISTS iss.t_producelinedetail;
DROP TABLE IF EXISTS iss.t_produceline;
DROP TABLE IF EXISTS iss.t_productcategoriesselltarget;
DROP TABLE IF EXISTS iss.t_productprice;
DROP TABLE IF EXISTS iss.t_reimbursepayment;
DROP TABLE IF EXISTS iss.t_scheduler;
DROP TABLE IF EXISTS iss.t_schedulerjob;
DROP TABLE IF EXISTS iss.t_selltarget;
DROP TABLE IF EXISTS iss.t_shoppingdetail;
DROP TABLE IF EXISTS iss.t_shopping;
DROP TABLE IF EXISTS iss.t_stackcoderelevance;
DROP TABLE IF EXISTS iss.t_storagedamaged;
DROP TABLE IF EXISTS iss.t_tagpricedamage;
DROP TABLE IF EXISTS iss.t_tagpriceinstorage;
DROP TABLE IF EXISTS iss.t_transfergoods;
DROP TABLE IF EXISTS iss.t_transfergoodsdetail;
DROP TABLE IF EXISTS iss.t_zpayment;
DROP TABLE IF EXISTS iss.t_product;
DROP TABLE IF EXISTS iss.t_productcategories;
DROP TABLE IF EXISTS t_warehouse;
DROP TABLE IF EXISTS t_warehouselocation;
DROP TABLE IF EXISTS t_warehouselocationstorage;
DROP TABLE IF EXISTS t_warehouselocationstoragedetail;
